# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowaviso.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_windowaviso(object):
    def setupUi(self, windowaviso):
        windowaviso.setObjectName("windowaviso")
        windowaviso.setWindowModality(QtCore.Qt.ApplicationModal)
        windowaviso.resize(288, 174)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../.designer/backup/img/warning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        windowaviso.setWindowIcon(icon)
        windowaviso.setStyleSheet("background-color: rgb(235, 235, 235);")
        windowaviso.setModal(True)
        self.btnBoxAviso = QtWidgets.QDialogButtonBox(windowaviso)
        self.btnBoxAviso.setGeometry(QtCore.QRect(50, 110, 161, 16))
        self.btnBoxAviso.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"selection-background-color: rgb(255, 255, 255);")
        self.btnBoxAviso.setOrientation(QtCore.Qt.Horizontal)
        self.btnBoxAviso.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.btnBoxAviso.setCenterButtons(True)
        self.btnBoxAviso.setObjectName("btnBoxAviso")
        self.lblAviso = QtWidgets.QLabel(windowaviso)
        self.lblAviso.setGeometry(QtCore.QRect(70, 70, 140, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.lblAviso.setFont(font)
        self.lblAviso.setStyleSheet("border-color: rgb(0, 85, 255);\n"
"font: 11pt \"Arial\";")
        self.lblAviso.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lblAviso.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAviso.setWordWrap(False)
        self.lblAviso.setObjectName("lblAviso")
        self.lblmageAviso = QtWidgets.QLabel(windowaviso)
        self.lblmageAviso.setGeometry(QtCore.QRect(110, 10, 51, 41))
        self.lblmageAviso.setText("")
        self.lblmageAviso.setPixmap(QtGui.QPixmap("img/warning.png"))
        self.lblmageAviso.setScaledContents(True)
        self.lblmageAviso.setObjectName("lblmageAviso")

        self.retranslateUi(windowaviso)
        self.btnBoxAviso.accepted.connect(windowaviso.accept)
        self.btnBoxAviso.rejected.connect(windowaviso.reject)
        QtCore.QMetaObject.connectSlotsByName(windowaviso)

    def retranslateUi(self, windowaviso):
        _translate = QtCore.QCoreApplication.translate
        windowaviso.setWindowTitle(_translate("windowaviso", "Aviso"))
        self.lblAviso.setText(_translate("windowaviso", "Desea Salir?"))
